{
  "openapi": "3.1.0",
  "info": {
    "title": "REST API - Body Auth",
    "version": "unknown"
  },
  "servers": [
    {
      "url": "https://sandbox.eupago.pt/clientes/rest_api"
    }
  ],
  "components": {
    "securitySchemes": {}
  },
  "security": [
    {}
  ],
  "paths": {
    "/multibanco/create": {
      "post": {
        "summary": "Multibanco",
        "description": "Creates Multibanco payment references:\n- with or without payment deadline\n- define an amount or an interval with max/min amounts to receive the payment\n- may choose if the references allow only 1 or more that 1 payment",
        "operationId": "multibanco",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "chave",
                  "valor",
                  "per_dup"
                ],
                "properties": {
                  "chave": {
                    "type": "string",
                    "description": "API Key"
                  },
                  "valor": {
                    "type": "number",
                    "description": "Amount",
                    "format": "float"
                  },
                  "id": {
                    "type": "string",
                    "description": "Identifier"
                  },
                  "data_inicio": {
                    "type": "string",
                    "description": "Reference starts to allow payments on this day (YYYY-MM-DD)",
                    "format": "date"
                  },
                  "data_fim": {
                    "type": "string",
                    "description": "Payment deadline (YYYY-MM-DD)",
                    "format": "date"
                  },
                  "valor_maximo": {
                    "type": "number",
                    "description": "Maximum amount (only for references that allow payments in an interval of amounts)",
                    "format": "float"
                  },
                  "valor_minimo": {
                    "type": "number",
                    "description": "Minimum amount (only for references that allow payments in an interval of amounts)",
                    "format": "float"
                  },
                  "per_dup": {
                    "type": "integer",
                    "description": "Defines if the reference allows 1 payment or more that 1 payment (1 = allows multiple payments | 0 = allows only 1 payment)",
                    "format": "int32"
                  },
                  "campos_extra": {
                    "type": "array",
                    "description": "Use this object to assign extra fields. Note that extra fields must be first setted up on your account channel.",
                    "items": {
                      "properties": {
                        "id": {
                          "type": "integer",
                          "description": "Number of your extra field",
                          "format": "int32"
                        },
                        "valor": {
                          "type": "string",
                          "description": "Value that should be assigned to this extra field for this reference."
                        }
                      },
                      "required": [
                        "id",
                        "valor"
                      ],
                      "type": "object"
                    }
                  },
                  "failOver": {
                    "type": "string",
                    "description": "Send a reminder to your customer that their payment has expired (Only available on references with deadline).",
                    "enum": [
                      "0",
                      "1"
                    ]
                  },
                  "email": {
                    "type": "string",
                    "description": "User email to receive the reminder notification (Only if failover = 1)."
                  },
                  "contacto": {
                    "type": "string",
                    "description": "User phone number to receive the reminder notification (Only if failover = 1)."
                  },
                  "userID": {
                    "type": "string",
                    "description": "User identifier parameter. (Mandatory for some clients)"
                  }
                }
              },
              "examples": {
                "Without Deadline - Interval of Amounts": {
                  "value": {
                    "chave": "xxxx-xxxx-xxxx-xxxx-xxxx",
                    "valor": "0",
                    "id": "Exemplo-em-JSON",
                    "valor_minimo": "5",
                    "valor_maximo": "122.5",
                    "per_dup": "0"
                  }
                },
                "With Deadline - Specific Amount": {
                  "value": {
                    "chave": "xxxx-xxxx-xxxx-xxxx-xxxx",
                    "valor": "10.5",
                    "id": "Example-em-JSON",
                    "data_inicio": "2021-10-28",
                    "data_fim": "2021-11-01",
                    "per_dup": "0"
                  }
                },
                "Extra Fields": {
                  "value": {
                    "campos_extra": [
                      {
                        "id": 369,
                        "valor": "um valor"
                      },
                      {
                        "id": 178,
                        "valor": "outro valor"
                      }
                    ],
                    "chave": "xxxx-xxxx-xxxx-xxxx-xxxx",
                    "valor": "3",
                    "id": "Exemplo2",
                    "per_dup": "0"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": "{\n    \"sucesso\": true,\n    \"estado\": 0,\n    \"resposta\": \"OK\",\n    \"referencia\": \"123456789\",\n    \"valor\": \"0.00000\",\n    \"entidade\": \"12345\",\n    \"valor_minimo\": \"5\",\n    \"valor_maximo\": \"122.5\",\n    \"data_inicio\": \"2021-10-28\",\n    \"data_fim\": \"2099-12-31\"\n}"
                  },
                  "Invalid API Key": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Chave de API inválida.\"\n}"
                  },
                  "Invalid Data": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Os dados inseridos não são válidos\"\n}"
                  }
                },
                "schema": {
                  "oneOf": [
                    {
                      "title": "Success",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": true,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": 0,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "OK"
                        },
                        "referencia": {
                          "type": "string",
                          "example": "123456789"
                        },
                        "valor": {
                          "type": "string",
                          "example": "0.00000"
                        },
                        "entidade": {
                          "type": "string",
                          "example": "12345"
                        },
                        "valor_minimo": {
                          "type": "string",
                          "example": "5"
                        },
                        "valor_maximo": {
                          "type": "string",
                          "example": "122.5"
                        },
                        "data_inicio": {
                          "type": "string",
                          "example": "2021-10-28"
                        },
                        "data_fim": {
                          "type": "string",
                          "example": "2099-12-31"
                        }
                      }
                    },
                    {
                      "title": "Invalid API Key",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Chave de API inválida."
                        }
                      }
                    },
                    {
                      "title": "Invalid Data",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Os dados inseridos não são válidos"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/mbway/create": {
      "post": {
        "summary": "MB WAY",
        "description": "Creates MB WAY payment requests.",
        "operationId": "mb-way",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "chave",
                  "valor",
                  "alias"
                ],
                "properties": {
                  "chave": {
                    "type": "string",
                    "description": "API Key"
                  },
                  "valor": {
                    "type": "number",
                    "description": "Amount",
                    "format": "float"
                  },
                  "id": {
                    "type": "string",
                    "description": "Identifier"
                  },
                  "alias": {
                    "type": "string",
                    "description": "Phone number that is connected to the MB WAY app and will pay"
                  },
                  "descricao": {
                    "type": "string",
                    "description": "Optional text that may appear on the payment request (e.g.: store name)"
                  },
                  "failOver": {
                    "type": "string",
                    "description": "Send a reminder to your customer that their payment has expired.",
                    "enum": [
                      "0",
                      "1"
                    ]
                  },
                  "email": {
                    "type": "string",
                    "description": "User email to receive the reminder notification (Only if failover = 1)."
                  },
                  "contacto": {
                    "type": "string",
                    "description": "User phone number to receive the reminder notification (Only if failover = 1)."
                  }
                }
              },
              "examples": {
                "Example": {
                  "value": {
                    "chave": "xxxx-xxxx-xxxx-xxxx-xxxx",
                    "valor": "12.95",
                    "id": "Exemplo-em-JSON",
                    "alias": "987654321",
                    "descricao": "exemplo eupago"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": "{\n    \"sucesso\": true,\n    \"estado\": 0,\n    \"resposta\": \"OK\",\n    \"referencia\": 8870231,\n    \"valor\": \"12.95000\",\n    \"alias\": \"351#987654321\"\n}"
                  },
                  "Invalid API Key": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Chave de API inválida.\"\n}"
                  },
                  "Invalid Data": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -9,\n    \"resposta\": \"Impossível gerar referência com os valores fornecidos.\",\n    \"alias\": \"351#911111111\",\n    \"valor\": null,\n    \"referencia\": \"0\"\n}"
                  },
                  "Incorrect Phone Number": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": \"-9\",\n    \"resposta\": \"Alias inexistente\",\n    \"alias\": \"351#999999999\"\n}"
                  },
                  "Missing Params": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Faltam parâmetros obrigatórios\"\n}"
                  }
                },
                "schema": {
                  "oneOf": [
                    {
                      "title": "Success",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": true,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": 0,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "OK"
                        },
                        "referencia": {
                          "type": "integer",
                          "example": 8870231,
                          "default": 0
                        },
                        "valor": {
                          "type": "string",
                          "example": "12.95000"
                        },
                        "alias": {
                          "type": "string",
                          "example": "351#987654321"
                        }
                      }
                    },
                    {
                      "title": "Invalid API Key",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Chave de API inválida."
                        }
                      }
                    },
                    {
                      "title": "Invalid Data",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -9,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Impossível gerar referência com os valores fornecidos."
                        },
                        "alias": {
                          "type": "string",
                          "example": "351#911111111"
                        },
                        "valor": {},
                        "referencia": {
                          "type": "string",
                          "example": "0"
                        }
                      }
                    },
                    {
                      "title": "Incorrect Phone Number",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "string",
                          "example": "-9"
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Alias inexistente"
                        },
                        "alias": {
                          "type": "string",
                          "example": "351#999999999"
                        }
                      }
                    },
                    {
                      "title": "Missing Params",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Faltam parâmetros obrigatórios"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/payshop/create": {
      "post": {
        "summary": "Payshop",
        "description": "Creates Payshop payment references.\n\nThese references are paid in cash on a large Portuguese network.",
        "operationId": "payshop",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "chave",
                  "valor"
                ],
                "properties": {
                  "chave": {
                    "type": "string",
                    "description": "API Key"
                  },
                  "valor": {
                    "type": "number",
                    "description": "Amount",
                    "format": "float"
                  },
                  "id": {
                    "type": "string",
                    "description": "Identifier"
                  }
                }
              },
              "examples": {
                "Example": {
                  "value": {
                    "chave": "xxxx-xxxx-xxxx-xxxx-xxxx",
                    "valor": "12.95",
                    "id": "Exemplo-em-JSON"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": "{\n    \"sucesso\": true,\n    \"estado\": 0,\n    \"resposta\": \"OK\",\n    \"referencia\": 3210835700635,\n    \"valor\": \"12.95000\"\n}\n"
                  },
                  "Invalid API Key": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Chave de API inválida.\"\n}"
                  },
                  "Invalid Data": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Os dados inseridos não são válidos\"\n}"
                  },
                  "Missing Params": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -9,\n    \"resposta\": \"Impossível gerar referência com os valores fornecidos.\"\n}"
                  }
                },
                "schema": {
                  "oneOf": [
                    {
                      "title": "Success",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": true,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": 0,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "OK"
                        },
                        "referencia": {
                          "type": "integer",
                          "example": 3210835700635,
                          "default": 0
                        },
                        "valor": {
                          "type": "string",
                          "example": "12.95000"
                        }
                      }
                    },
                    {
                      "title": "Invalid API Key",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Chave de API inválida."
                        }
                      }
                    },
                    {
                      "title": "Invalid Data",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Os dados inseridos não são válidos"
                        }
                      }
                    },
                    {
                      "title": "Missing Params",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -9,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Impossível gerar referência com os valores fornecidos."
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/paysafecard/create": {
      "post": {
        "summary": "Paysafecard",
        "description": "Creates Paysafecard payment references.",
        "operationId": "paysafecard",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "chave",
                  "valor"
                ],
                "properties": {
                  "chave": {
                    "type": "string",
                    "description": "API Key"
                  },
                  "valor": {
                    "type": "number",
                    "description": "Amount",
                    "format": "float"
                  },
                  "id": {
                    "type": "string",
                    "description": "Identifier"
                  },
                  "url_retorno": {
                    "type": "string",
                    "description": "Used to define the url to where the customer will be redirected he/she finishes the payment."
                  }
                }
              },
              "examples": {
                "Example": {
                  "value": {
                    "chave": "xxxx-xxxx-xxxx-xxxx",
                    "valor": "20",
                    "id": "Exemplo-em-JSON",
                    "url_retorno": "https://exemplo.pt"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Sucesso": {
                    "value": ""
                  },
                  "Invalid API Key": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Chave de API inválida.\"\n}"
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "sucesso": {
                      "type": "boolean",
                      "example": false,
                      "default": true
                    },
                    "estado": {
                      "type": "integer",
                      "example": -10,
                      "default": 0
                    },
                    "resposta": {
                      "type": "string",
                      "example": "Chave de API inválida."
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/cc/form": {
      "post": {
        "summary": "Credit Card 3DS",
        "description": "Creates a url to a secure form where the customer may finish the Credit Card payment. Uses 3D Secure Technology.",
        "operationId": "credit-card-3ds",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "chave",
                  "valor",
                  "tds"
                ],
                "properties": {
                  "chave": {
                    "type": "string",
                    "description": "API Key"
                  },
                  "valor": {
                    "type": "number",
                    "description": "Amount",
                    "format": "float"
                  },
                  "id": {
                    "type": "string",
                    "description": "Identifier"
                  },
                  "tds": {
                    "type": "integer",
                    "description": "Mandatory to define this parameter as 1 (it forces the use of 3D Secure Technology)",
                    "default": 1,
                    "format": "int32"
                  },
                  "url_logotipo": {
                    "type": "string",
                    "description": "Use to define a custom imagem to show your payment request."
                  },
                  "url_retorno": {
                    "type": "string",
                    "description": "Used to define the url to where the customer will be redirected he/she finishes the payment."
                  },
                  "nome": {
                    "type": "string",
                    "description": "Customer's Name"
                  },
                  "email": {
                    "type": "string",
                    "description": "Customer's Email"
                  },
                  "lang": {
                    "type": "string",
                    "description": "Form Language (pt / en)",
                    "default": "pt"
                  },
                  "comentario": {
                    "type": "string",
                    "description": "Optional text that will appear between the logo and the payment amount"
                  }
                }
              },
              "examples": {
                "Example": {
                  "value": {
                    "chave": "xxxx-xxxx-xxxx-xxxx-xxxx",
                    "valor": "154.21",
                    "id": "Exemplo-em-JSON",
                    "tds": "1"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": "{\n    \"sucesso\": true,\n    \"estado\": 0,\n    \"resposta\": \"OK\",\n    \"valor\": \"154.21000\",\n    \"token\": \"abc123\",\n    \"referencia\": \"000077275\",\n    \"url\": \"https://sandbox.eupago.pt/cc/form_cc.php?t=abc123\"\n}"
                  },
                  "Invalid API Key": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Chave de API inválida.\"\n}"
                  }
                },
                "schema": {
                  "oneOf": [
                    {
                      "title": "Success",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": true,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": 0,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "OK"
                        },
                        "valor": {
                          "type": "string",
                          "example": "154.21000"
                        },
                        "token": {
                          "type": "string",
                          "example": "abc123"
                        },
                        "referencia": {
                          "type": "string",
                          "example": "000077275"
                        },
                        "url": {
                          "type": "string",
                          "example": "https://sandbox.eupago.pt/cc/form_cc.php?t=abc123"
                        }
                      }
                    },
                    {
                      "title": "Invalid API Key",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Chave de API inválida."
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/multibanco/info": {
      "post": {
        "summary": "Reference Information",
        "description": "Check the status of a reference on Eupago.",
        "operationId": "reference-information",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "chave",
                  "referencia"
                ],
                "properties": {
                  "chave": {
                    "type": "string",
                    "description": "API Key"
                  },
                  "referencia": {
                    "type": "string",
                    "description": "Reference"
                  },
                  "entidade": {
                    "type": "string",
                    "description": "Entity (If it exists, Not all services have an entity)"
                  }
                }
              },
              "examples": {
                "Example": {
                  "value": {
                    "chave": "xxxx-xxxx-xxxx-xxxx",
                    "referencia": "123456789",
                    "entidade": "12345"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": "{\n    \"entidade\": \"12345\",\n    \"referencia\": \"123456789\",\n    \"identificador\": \"Exemplo-em-JSON\",\n    \"estado\": 0,\n    \"data_criacao\": \"2021-10-28\",\n    \"hora_criacao\": \"14:37:23\",\n    \"estado\": \"pendente\",\n    \"arquivada\": false,\n    \"sucesso\": true,\n    \"resposta\": \"OK\"\n}"
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "entidade": {
                      "type": "string",
                      "example": "12345"
                    },
                    "referencia": {
                      "type": "string",
                      "example": "123456789"
                    },
                    "identificador": {
                      "type": "string",
                      "example": "Exemplo-em-JSON"
                    },
                    "estado": {
                      "type": "string",
                      "example": "pendente"
                    },
                    "data_criacao": {
                      "type": "string",
                      "example": "2021-10-28"
                    },
                    "hora_criacao": {
                      "type": "string",
                      "example": "14:37:23"
                    },
                    "arquivada": {
                      "type": "boolean",
                      "example": false,
                      "default": true
                    },
                    "sucesso": {
                      "type": "boolean",
                      "example": true,
                      "default": true
                    },
                    "resposta": {
                      "type": "string",
                      "example": "OK"
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/mbway_refeicao/create": {
      "post": {
        "summary": "MB WAY Meal Passes",
        "description": "Creates MB WAY Meal Passes payment requests.",
        "operationId": "mb-way-meal-passes",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "chave",
                  "valor",
                  "alias"
                ],
                "properties": {
                  "chave": {
                    "type": "string",
                    "description": "API Key"
                  },
                  "valor": {
                    "type": "number",
                    "description": "Amount",
                    "format": "float"
                  },
                  "id": {
                    "type": "string",
                    "description": "Identifier"
                  },
                  "alias": {
                    "type": "string",
                    "description": "Phone number that is connected to the MB WAY app and will pay"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": "{\n    \"sucesso\": true,\n    \"estado\": 0,\n    \"resposta\": \"OK\",\n    \"referencia\": 8870231,\n    \"valor\": \"12.95000\",\n    \"alias\": \"351#987654321\"\n}"
                  },
                  "Invalid API Key": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Chave de API inválida.\"\n}"
                  },
                  "Invalid Data": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -9,\n    \"resposta\": \"Impossível gerar referência com os valores fornecidos.\",\n    \"alias\": \"351#911111111\",\n    \"valor\": null,\n    \"referencia\": \"0\"\n}"
                  },
                  "Incorrect Phone Number": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": \"-9\",\n    \"resposta\": \"Alias inexistente\",\n    \"alias\": \"351#999999999\"\n}"
                  },
                  "Missing Params": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Faltam parâmetros obrigatórios\"\n}"
                  }
                },
                "schema": {
                  "oneOf": [
                    {
                      "title": "Success",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": true,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": 0,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "OK"
                        },
                        "referencia": {
                          "type": "integer",
                          "example": 8870231,
                          "default": 0
                        },
                        "valor": {
                          "type": "string",
                          "example": "12.95000"
                        },
                        "alias": {
                          "type": "string",
                          "example": "351#987654321"
                        }
                      }
                    },
                    {
                      "title": "Invalid API Key",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Chave de API inválida."
                        }
                      }
                    },
                    {
                      "title": "Invalid Data",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -9,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Impossível gerar referência com os valores fornecidos."
                        },
                        "alias": {
                          "type": "string",
                          "example": "351#911111111"
                        },
                        "valor": {},
                        "referencia": {
                          "type": "string",
                          "example": "0"
                        }
                      }
                    },
                    {
                      "title": "Incorrect Phone Number",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "string",
                          "example": "-9"
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Alias inexistente"
                        },
                        "alias": {
                          "type": "string",
                          "example": "351#999999999"
                        }
                      }
                    },
                    {
                      "title": "Missing Params",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Faltam parâmetros obrigatórios"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/multibanco/apg": {
      "post": {
        "summary": "Multibanco DPG",
        "description": "Creates Multibanco payment references with a deadline, using check-digit. These references will only accept a single payment in a specific amount until they exceed their deadline.",
        "operationId": "multibanco-dpg",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "chave",
                  "valor",
                  "data_inicio",
                  "data_fim"
                ],
                "properties": {
                  "chave": {
                    "type": "string",
                    "description": "API Key"
                  },
                  "valor": {
                    "type": "number",
                    "description": "Amount",
                    "format": "float"
                  },
                  "id": {
                    "type": "string",
                    "description": "Identifier"
                  },
                  "data_inicio": {
                    "type": "string",
                    "description": "Reference starts to allow payments on this day (YYYY-MM-DD)",
                    "format": "date"
                  },
                  "data_fim": {
                    "type": "string",
                    "description": "Payment deadline (YYYY-MM-DD)",
                    "format": "date"
                  }
                }
              },
              "examples": {
                "Example": {
                  "value": {
                    "chave": "xxxx-xxxx-xxxx-xxxx-xxxx",
                    "valor": "10.5",
                    "id": "Test",
                    "data_inicio": "2022-06-29",
                    "data_fim": "2022-06-30"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Success": {
                    "value": "{\n    \"sucesso\": true,\n    \"estado\": 0,\n    \"resposta\": \"OK\",\n    \"referencia\": \"288006318\",\n    \"valor\": \"10.50000\",\n    \"entidade\": \"83189\",\n    \"valor_minimo\": \"10.5\",\n    \"valor_maximo\": \"10.5\",\n    \"data_inicio\": \"2022-06-29\",\n    \"data_fim\": \"2022-06-30\"\n}"
                  },
                  "Invalid API Key": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Chave de API inválida.\"\n}"
                  },
                  "Invalid Data": {
                    "value": "{\n    \"sucesso\": false,\n    \"estado\": -10,\n    \"resposta\": \"Os dados inseridos não são válidos\"\n}"
                  },
                  "Date with wrong format": {
                    "value": "{\n  \"sucesso\": false,\n  \"estado\": -7,\n  \"resposta\": \"Formato de data inv&aacute;lido. A data de in&iacute;cio deve estar no formato YYYY-MM-DD!\"\n}"
                  }
                },
                "schema": {
                  "oneOf": [
                    {
                      "title": "Success",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": true,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": 0,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "OK"
                        },
                        "referencia": {
                          "type": "string",
                          "example": "288006318"
                        },
                        "valor": {
                          "type": "string",
                          "example": "10.50000"
                        },
                        "entidade": {
                          "type": "string",
                          "example": "83189"
                        },
                        "valor_minimo": {
                          "type": "string",
                          "example": "10.5"
                        },
                        "valor_maximo": {
                          "type": "string",
                          "example": "10.5"
                        },
                        "data_inicio": {
                          "type": "string",
                          "example": "2022-06-29"
                        },
                        "data_fim": {
                          "type": "string",
                          "example": "2022-06-30"
                        }
                      }
                    },
                    {
                      "title": "Invalid API Key",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Chave de API inválida."
                        }
                      }
                    },
                    {
                      "title": "Invalid Data",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -10,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Os dados inseridos não são válidos"
                        }
                      }
                    },
                    {
                      "title": "Date with wrong format",
                      "type": "object",
                      "properties": {
                        "sucesso": {
                          "type": "boolean",
                          "example": false,
                          "default": true
                        },
                        "estado": {
                          "type": "integer",
                          "example": -7,
                          "default": 0
                        },
                        "resposta": {
                          "type": "string",
                          "example": "Formato de data inv&aacute;lido. A data de in&iacute;cio deve estar no formato YYYY-MM-DD!"
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    }
  },
  "x-readme": {
    "headers": []
  },
  "x-readme-fauxas": true
}